version: "3"

services:
  web-server:
    image: nginx:latest
    networks: [wordpress]
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    ports: ["8000:80"]
    logging:
        driver: none

  php-fpm:
    image: polyverse/polyscripted-wordpress:alpine-$headsha
    networks: [wordpress]
    volumes: 
        - ./wordpress:/wordpress
    environment:
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_HOST=db
      - MODE=$MODE
  
  db:
    image: mysql:5.7
    networks: [wordpress]
    environment: [MYSQL_ROOT_PASSWORD=secret]
    logging:
        driver: none

volumes:
  database:
  wordpress:

# Containers are united into single network by default, but won't access each
# other by hostname without an explicitly declared network.
networks:
  wordpress:
